sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t manusil/docker-react-app -f Dockerfile.dev .

script:
  - docker runt -e CI:true manusil/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"